"""add patients and appointments tables

Revision ID: 2865d36f3856
Revises: a20972001a0c
Create Date: 2025-10-26 13:28:29.878736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2865d36f3856'
down_revision = 'a20972001a0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
