"""delete email

Revision ID: 85753828fc7c
Revises: 1a89f300adf1
Create Date: 2025-10-27 21:16:14.856156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85753828fc7c'
down_revision = '1a89f300adf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
