"""Add surgeries table

Revision ID: 8a5abf647178
Revises: d2acbe15e733
Create Date: 2025-10-28 00:24:46.876967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5abf647178'
down_revision = 'd2acbe15e733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
