"""Add billing tables

Revision ID: c456bfe52342
Revises: c955712d776e
Create Date: 2025-10-28 00:48:40.035034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c456bfe52342'
down_revision = 'c955712d776e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
