"""Add stats tables

Revision ID: c955712d776e
Revises: 216f56a128d9
Create Date: 2025-10-28 00:35:44.193621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c955712d776e'
down_revision = '216f56a128d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('widget_name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_stats_id'), 'dashboard_stats', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_stats_widget_type'), 'dashboard_stats', ['widget_type'], unique=False)
    op.create_table('system_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=False),
    sa.Column('stat_key', sa.String(length=100), nullable=False),
    sa.Column('int_value', sa.Integer(), nullable=True),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_stats_id'), 'system_stats', ['id'], unique=False)
    op.create_index(op.f('ix_system_stats_stat_key'), 'system_stats', ['stat_key'], unique=False)
    op.create_index(op.f('ix_system_stats_stat_type'), 'system_stats', ['stat_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_stats_stat_type'), table_name='system_stats')
    op.drop_index(op.f('ix_system_stats_stat_key'), table_name='system_stats')
    op.drop_index(op.f('ix_system_stats_id'), table_name='system_stats')
    op.drop_table('system_stats')
    op.drop_index(op.f('ix_dashboard_stats_widget_type'), table_name='dashboard_stats')
    op.drop_index(op.f('ix_dashboard_stats_id'), table_name='dashboard_stats')
    op.drop_table('dashboard_stats')
    # ### end Alembic commands ###
