"""remove email field from patients

Revision ID: remove_email_from_patients
Revises: 1a89f300adf1
Create Date: 2025-10-27 16:12:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_email_from_patients'
down_revision = '1a89f300adf1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###alembic upgrade head
